apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: ci
  annotations:
    kubernetes.io/ingress.class: nginx
    # Add to generate certificates for this ingress
    kubernetes.io/tls-acme: 'true'
spec:
  rules:
    - host: ci.reboot3times.org
      http:
        paths:
          - backend:
              serviceName: jenkins-ui
              servicePort: 8080
            path: /
  tls:
    # With this configuration kube-lego will generate a secret in namespace foo called `example-tls`
    # for the URL `www.example.com`
    - hosts:
        - "ci.reboot3times.org"
      secretName: jenkins-tls